#@host = http://127.0.0.1:5000

@host = https://chajim.pythonanywhere.com/ 
### GET simple aplive check
GET {{host}}


### POST Login
# @name login
POST {{host}}/login
Content-Type: application/json

{"username": "{{DEBUG_USER2}}", "password": "{{DEBUG_PASS2}}"}

### Use the login token in the next
@token = {{login.response.body.$.id}}

### POST Register
POST {{host}}/register
Content-Type: application/json

{"username": "{{DEBUG_USER2}}", "password": "{{DEBUG_PASS2}}"}

### POST Save entry
POST {{host}}/save_entry
Content-Type: application/json
Authorization: Bearer {{token}}

{"id" : "{{token}}", "text": "Had a good lunch today. Saw a stranger get robbed, poor fella.", "emotions" : "Good"}

### POST Get emotions
POST {{host}}/get_emotions
Content-Type: application/json
Authorization: Bearer {{token}}

{"id" : "{{token}}", "text": "Had a good lunch today. Saw a stranger get killed, poor fella.", "emotions" : "Good"}


### POST Add friend 
POST {{host}}/add_friend
Content-Type: application/json
Authorization: Bearer {{token}}

{"id" : "{{token}}", "friend_name" : "{{DEBUG_USER1}}"}


### POST Get post with title
POST {{host}}/get_post_with_title
Content-Type: application/json
Authorization: Bearer {{token}}

{"id" : "{{token}}", "entry_id" : "65"}

### POST Get batch get posts
POST {{host}}/batch_get_posts
Content-Type: application/json
Authorization: Bearer {{token}}

{"id" : "{{token}}", "entry_ids" : [2,3]}





